export default dataCourses=[
    {
        image:require('../Assets/image/flame.png'),
        title:'Abstract Design',
        text:'We are going to learn how to use Acrylic paint to create abstract textures and modify them in Photoshop',
        percentage:76,
        one:require('../Assets/image/1.jpg'),
        two:require('../Assets/image/2.jpg'),
        three:require('../Assets/image/3.jpg'),
        four:require('../Assets/image/4.jpg'),
    },
    {
        image:require('../Assets/image/sky.png'),
        title:'Industrial Design',
        text:'This class is an encouraging , empowering experience that will change the way you look at objects all around you',
        percentage:32,
        one:require('../Assets/image/5.jpg'),
        two:require('../Assets/image/6.jpg'),
        three:require('../Assets/image/7.jpg'),
        four:require('../Assets/image/8.jpg'),
    },
    {
        image:require('../Assets/image/lens.png'),
        title:'Photography',
        text:'It include working with lighting at different times of day and incorporating subjects into a landscape shot',
        percentage:46,
        one:require('../Assets/image/9.jpg'),
        two:require('../Assets/image/10.jpg'),
        three:require('../Assets/image/11.jpg'),
        four:require('../Assets/image/12.jpg'),
    },
    {
        image:require('../Assets/image/charts.png'),
        title:'Marketing & Finance',
        text:'This class is an encouraging , empowering experience that will change the way you look at objects all around you',
        percentage:12,
        one:require('../Assets/image/1.jpg'),
        two:require('../Assets/image/2.jpg'),
        three:require('../Assets/image/3.jpg'),
        four:require('../Assets/image/4.jpg'),
    },
    {
        image:require('../Assets/image/ice.png'),
        title:'3D Art',
        text:'This class is an encouraging , empowering experience that will change the way you look at objects all around you',
        percentage:82,
        one:require('../Assets/image/5.jpg'),
        two:require('../Assets/image/6.jpg'),
        three:require('../Assets/image/7.jpg'),
        four:require('../Assets/image/8.jpg'),
    },

    {
        image:require('../Assets/image/girl.png'),
        title:'Fine Art',
        text:'This class is an encouraging , empowering experience that will change the way you look at objects all around you',
        percentage:67,
        one:require('../Assets/image/9.jpg'),
        two:require('../Assets/image/10.jpg'),
        three:require('../Assets/image/11.jpg'),
        four:require('../Assets/image/12.jpg'),
    }
]